### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ErmitaVulpe** [Togeee12/JavaScript-CodeWeek#1]
### Todo
- [ ] Implement auto localization using the built-in browser localization API and the Google Maps API
- [ ] Add a 5-day weather forecast
- [ ] Improve UI/UX
