### ISSUE TITLE
#2 TODO -> Tic-tac-toe

### ISSUE THREAD

**Issue by Togeee12** [Togeee12/JavaScript-CodeWeek#4]
#TODO: 

- [ ] Scoreboard using localstorage
- [ ] Create a dark theme
- [ ] Add theme switch
